# BC_INIT: false
DEMO_FILE: ../demonstrations/relocate-large_clamp.pkl
ENV_NAME: relocate-large_clamp-0.8
JOB_DIR: ./training_log
JOB_NAME: trpo
NUM_ITER: 2000
POLICY_INIT_LOG_STD: 0.0
POLICY_WS:
- 32
- 32
RNG_SEED: 100
# SAVE_FREQ: 100
NUM_CPU: 8
SOIL:
  ADV_W: 0.1
  ENABLED: true
  LAM0: 0.01
  LAM1: 0.99
  LR: 1e-3
  MB_SIZE: 32
  MLP_W: 64
  NUM_ITER: 500
  RBS: 1000000
  WD: 0.0


#New configurations
#####################################
BC_INIT: true
USE_DAPG: false
USE_INVDYN_ONPG: true

SAVE_FREQ: 5
# CHECKPOINT_POLICY: "/home/xiaoyu/Desktop/yogee/dexmv-sim/trained_model/best_1000.pickle"
# CHECKPOINT_BASELINE: true
######################################




# Using Custom fingers
######################################
INVDYN_ONPG_SUBSET: true
INVDYN_ONPG_ACT_SUBSET: true
CUSTOM_FINGERS: true
# SDAPG_OBS_R: 27
# AFF_OBS_R: 27
# GASIL_OBS_R: 27
#######################################
